name: coordinated_page_route
description: A dart package for Flutter that allows co-ordinated page transitions that animate the previous route as well as the incoming route.
version: 0.0.1
homepage: https://github.com/arrowsmith001/coordinated_page_route

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
